export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_TO_CART = "REMOVE_TO_CART"
export const LIST_PRODUCTS = "LIST_PRODUCTS"
export const ADD_LIST_PRODUCTS = "ADD_LIST_PRODUCTS"
export const GetProduct = "GetProduct"